icondir = get_option('datadir') / 'icons' / 'hicolor'
symbolicdir = icondir / 'symbolic' / 'apps'
scalabledir = icondir / 'scalable' / 'apps'

install_data(
  'io.github.nacho.teclazo.svg',
  install_dir: scalabledir,
)

install_data(
  'io.github.nacho.teclazo-symbolic.svg',
  install_dir: symbolicdir,
)
